### PR TITLE
Disable environment variable reporting by default

### PR DESCRIPTION
**Pull request by mattdrees**
We're increasingly using environment variables pass in passwords. So, don't record all environment variables by default. 

[MISC-219](https://jira.cru.org/browse/MISC-219)

This PR also includes a few version updates and fixes two tests that were failing on the CI server.

### CODE REVIEW

**Comment by mattdrees** [comment]
@ryancarlson would you be up for reviewing this?

**Comment by ryancarlson** [comment]
certainly!

**Comment by ryancarlson** [comment]
Cool so the gist here is that environment variables are no longer recorded by default, and users can opt in to sending them.  Seems pretty simple and straightforward.  +1 for updating the readme with a very clear explanation!

**Comment by mattdrees** [comment]
Yep, that's the gist.
Thanks!

**Comment by ryancarlson** [comment]
:+1:

**Pull request merged**
