### PR TITLE
Misc updates for EP usability

### PR DESCRIPTION
**Pull request by mattdrees**
The main goal here is to make long exception chains, which are often caused by Spring etc in Elastic Path, easier to view in the Rollbar UI. So this adjusts the title and the order of exceptions sent to the API.

There's also a tweak to the datadog link logic.

But this also finishes out some maintenance work I started, but didn't finish, a while back. I wanted to update to Rollbar's latest SDK, and I also wanted to remove Joda time.

### CODE REVIEW

**Review by hlbraddock — APPROVED** [review]

**Comment by hlbraddock** [comment]
Let's wait for the Jenkins build to succeed in stage/nonprod and QA there first, before we merge/deploy.

**Comment by hlbraddock** [comment]
Nice work!

**Comment by mattdrees** [comment]
Ok, this deployed to stage about 40m ago. I'll run the datadog synthetics checks, and if those pass I think we should consider QA complete.

**Comment by mattdrees** [comment]
A recent socket timeout for match-and-create looks pretty good: https://app.rollbar.com/a/Cru/fix/item/give-ep/14283#detail

**Comment by mattdrees** [comment]
OK, those passed. Going to merge and deploy to artifactory.

**Pull request merged**
